import "./globals.css";
import type { Metadata } from "next";
import { TheHeader } from "@/components/Header/TheHeader";
import { TheFooter } from "@/components/Footer/TheFooter";

export const metadata: Metadata = {
  title: "Addic42",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <body>
        <TheHeader />
        <main>{children}</main>
        <TheFooter />
      </body>
    </html>
  );
}
